### ISSUE TITLE
When using multi gpu to test the trained model, mAP and rank-1 descended.

### ISSUE THREAD

**Issue by HongweiZhang97** [automan000/Camera-based-Person-ReID#4]
Hello，I find that when using multi gpu to test the trained model, mAP and rank-1 descended. Is this normal？Could you provide some possible explanations？

**Comment by automan000** [comment]
Hi,
It's quite normal. Please test our model with a single GPU.
The problem is within the BN estimation in the testing stage. 
For the current implementation, testing with multiple GPUs means that each mini-batch will be split into smaller chunks, sent to each GPU, and used for calculating BN statistics separately. 
However, the BN statistics are not synced across multiple GPUs, and the final results are from only one GPU. They are less accurate.
Using Synchronized Batch Normalization may solve this problem.
Please feel free to share your results.
